### ISSUE TITLE
Garbled layout in dashboard after adding two voters

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/mainstream_relational_gotv#10]
I don't know what combination of variables produced this. When I added one contact, the layout was great. When I matched that one contact, it was also great. But when I added a sec0nd contact, it came in all weird.

First, the layout is jumbled up on top of the previous contact a little, with two hr lines below, so there may be some formatting code mixed up.

Second, the new contact came in with a full set of task options, like they had been matched, when they had not yet. Deleting one contact (I deleted the one I had matched) results in a clean layout again, with the unmatched contact shown with just the unmatched options.

Here are two screenshots:

First, with two contacts so you can see the layout errors:

<img width="959" alt="screen shot 2018-05-29 at 12 08 53 pm" src="https://user-images.githubusercontent.com/38695722/40674143-92eb154a-6339-11e8-919f-a259d5ccf1ec.png">

Second, when I deleted the first contact, so you can see how the errors fixed themselves nicely.

<img width="905" alt="screen shot 2018-05-29 at 12 10 49 pm" src="https://user-images.githubusercontent.com/38695722/40674149-993e8544-6339-11e8-88b2-db17b5dace65.png">

**Comment by jakelowen** [comment]
Yea.. I've already noted this one and opened issue #1 .  I'll close this one and take care of it there.
