### ISSUE TITLE
Not convinced about the usefulness of the iframe on the dashboard

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/mainstream_relational_gotv#13]
(Not sure you're using an iframe, per se, but that's the behavior)

The list of contacts in the dashboard exist within their own scrollable frame in the page. But there have been a handful of times when I have wondered where the rest of my contacts are, because I have inadvertently scrolled the page with the cursor outside of the frame. So, the page does scroll, but only as far as the sidebar div requires, then the footer appears. If I move the cursor to the iframe portion, and scroll, it scrolls within the page. But that isn't terribly discoverable, and the interaction between the sidebar being longer than the viewport causing scrolling of the entire page, and the iframe scrolling can be counterintuitive at times.

I guess what I'm saying is, why not just render the contacts directly on the page, in the div the iframe is currently in, instead of within the frame? I'd prefer that as an interface, for this layout.

Again, apologies for not seeing this before forking. I guess I hadn't added more than a few contacts at one time except that once I was testing the 10 pts for ten contacts rule.

**Comment by jakelowen** [comment]
What you are describing is not an Iframe, but I could see the parallels in how they respond to scrolling.

I certainly could render the list members directly on the page, but I opted for "virtualizing" the list here via react-virtualized (http://www.reactvirtualized.com/)  This is way overkill for 10 contacts, but if a user were to add 50, 100 or more contacts, we'd definitely need this approach.

The basic idea is that we create an active "viewing window" which is aware of which rows are currently being viewed. As you scroll down the list it renders the next rows "just in time" and un-renders any rows not in view. This prevents all the non-visible rows from junking up and slowing down the DOM.  I'm just concerned with how "complex" each row is between all the modals, status buttons etc to allow many more than just a few to exist at any given moment.

But if you feel strongly that it detracts from experience I can try a direct render.  The only other potential alternative is to paginate results, but that would also introduce another form of UI complexity

**Comment by MainStreamDanny** [comment]
Okay, I see now. It just felt like an iframe because I couldn't see the just in time rendering.

Let's leave it. We can revisit next year if it was a problem.

**Comment by jakelowen** [comment]
Cool. Closing for now.
