### ISSUE TITLE
Can one org have more than one admin?

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/mainstream_relational_gotv#15]
Meaning, is there anything preventing two people from having admin privs for one org? All it gives them is access to the admin_notes field, right? Practically speaking.

**Comment by MainStreamDanny** [comment]
From a db standpoint, I can see how it would be possible. It checks the logged in user's permissions, if they have ADMIN it displays the admin_notes.

But I can also see where it's a PITA for displaying org contact info for ambassadors or people looking to register. Could be fixed with a loop that just displays a second set of contact info if the query results n more than one, I guess. Layout might be a little compromised, but maybe not.

I think we'd like to have the option of more than one org contact person, if we can.

**Comment by jakelowen** [comment]
So permissions are completely separate idea from the displayed contact for an org.  Currently each org only has one slot for contact name.  However, an org can have unlimited users. As many of those users as you want to give admin access to may have it. Just be careful who you give the keys to.

**Comment by MainStreamDanny** [comment]
So, if I give ADMIN to two users in the same org, which one will show as the contact in the interface? The first one alphabetically?
