### ISSUE TITLE
Welp, the list of orgs on the home page is "Error!" again

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/mainstream_relational_gotv#17]
The home page is throwing the "Error!" error where the sit of orgs should be. I checked the db, and all the fields have something in them (except admin_notes, that still has NULLs)

I'm guessing you know about this already.

<img width="1052" alt="screen shot 2018-05-31 at 11 14 19 am" src="https://user-images.githubusercontent.com/38695722/40794100-d1bc451a-64c3-11e8-8661-82e195856795.png">

**Comment by jakelowen** [comment]
Sorry. I messed with the database on danny's org to remove phone, so I could test the conditional phone rendering. All works on my local version but the production version will error until I push this deploy... I will do that now.

**Comment by MainStreamDanny** [comment]
No problem.
