### ISSUE TITLE
Link to heroku data?

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/mainstream_relational_gotv#19]
For the admin_notes field, I need a link to the heroku db for the orgs. How would I find that? I assume it is different for each org?

**Comment by jakelowen** [comment]
Yes.. I'll need to write those dataclips now that we have a heroku database in production.  Can you open issues for each kind of dataclip we need to exist and I will write those now?  (Not an issue for each org, but just like  - admin data view 1 - list of ambassadors and their points, include x,y,z)
