### ISSUE TITLE
Home page list of partners shows Error!

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/mainstream_relational_gotv#2]
I added partners via the db directly, and the home page of the project does not list them Instead, it lists "Error!"
<img width="1021" alt="screen shot 2018-05-29 at 9 39 05 am" src="https://user-images.githubusercontent.com/38695722/40665938-2bcbb62c-6324-11e8-9cf7-93847fcfc0c5.png">

**Comment by jakelowen** [comment]
@MainStreamDanny - As it stands, each org must have 

- name
- slug
- cta
- contact name
- contact email
- contact phone

If any org is missing any of above, it will unfortunately throw that error. I can ease this if any of the above is more "optional" in your mind.

**Comment by jakelowen** [comment]
ok.. closing this one for now. ( I do see your other issue about phone)
