### ISSUE TITLE
How are orgs ordered on the home page?

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/mainstream_relational_gotv#20]
What is the ordering of orgs on the home page (now the list is back, thank you)? It's not alpha by first letter of the name field. It's not by date added... :)

**Comment by jakelowen** [comment]
I'm not currently specifying the sort order. Feel free to request one.

**Comment by MainStreamDanny** [comment]
Very _laissez faire_ of you. Let's do it by the name field in the organizations table.
