### ISSUE TITLE
Unmatched contacts do not have new edit and delete links

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/mainstream_relational_gotv#21]
Just on oversight, I bet. When a contact is added but not yet matched, they don't have the (Edit) and (Delete) links.

**Comment by jakelowen** [comment]
Ha.. oops. I removed those buttons when I swapped over to the new style requested in #14. When I put them back do you want them as buttons like before or as text links like you see with linked records?  One advantage of eliminating those buttons is that reduces and entire column from each row.

**Comment by MainStreamDanny** [comment]
Text links are fine. Can you make them 0.7 em or something, just a little smaller than the name?
