### ISSUE TITLE
Data requests: entire cohort

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/mainstream_relational_gotv#22]
We'd like a database to view/download with the entire set of data, so each ambassador and each of their voters for a given organization. All the stuff. Probably along these lines?

For org1

ambassador1 all/the/ambassador/data voter1 all/the/voter/data
ambassador1 all/the/ambassador/data voter2 all/the/voter/data
ambassador1 all/the/ambassador/data voter3 all/the/voter/data
ambassador2 all/the/ambassador/data voter1 all/the/voter/data
ambassador2 all/the/ambassador/data voter2 all/the/voter/data
etc...

**Comment by jakelowen** [comment]
How does this look:
https://dataclips.heroku.com/rvcopsxkmlakirdfufpvgojeiqpk-MainStream-Coalition-entire-cohort

This is an example dataclip for just one organization.

**Comment by MainStreamDanny** [comment]
This looks pretty good, yes. As a start. Is this live? Or is this dummy data?

—
Danny Novo
Communications Coordinator
MainStream Coalition
