### ISSUE TITLE
Roll out task for unmatched contacts?

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/mainstream_relational_gotv#24]
We have some concerns about the delay in matching, in that people who we get to register to vote won't be matchable until the file is updated, but we'd like to engage them in the other tasks, like applying for an advance ballot. Given that we keep both sets of data (before and after matching) can we roll out tasks for people who are not matched? Is that big change?

**Comment by jakelowen** [comment]
I don't think that would be a big problem.. Here is how the logic roughly flows now when choosing what to display on the tasks modal:

1. Is the contact matched to a voter file record?
    - NO.. Then show a static message about needing to match first.
    - YES...  Proceed to 2.
2. Does the contact have at least 1 task (of any completion status)
    --  No. Show a happy little "All done for today" message.
    --  YES.. Then show tasks table, allow them to choose one.

So... no, I don't think it would be too hard to add in tasks for unmatched, but we would want to think very carefully about how we want to handle the "Register this person to vote first" tasks (which we currently handle by forcing them essentially into the registration modal).  It might be dangerous to allow them to move on to other tasks until we can confirm registration.  Going to close this for now, but lets reopen or create a new issue when we have a plan.

**Comment by MainStreamDanny** [comment]
Of the five tasks we have right now, some are clearly dependent on being registered, and some are not. If not, we can definitely show them to the users. But the ones that **_are_** dependent suffer if we are not _sure_ if they are registered yet. Someone could have registered, and could apply for VBM, but might not yet show up in the voter file (or we might not have uploaded it yet). Not sure what to do about those.

Not voter file dependent:

- Tell this voter about the upcoming election
- Forward inspirational stories about why voting is important
- Make sure this voter has a plan to vote

Voter file dependent:

- Help this voter submit a vote by mail application
- Share a sample ballot with this voter

**Comment by MainStreamDanny** [comment]
So, what I envision is the user hits Tasks, and sees a list of all the tasks, as they do now.

First on the list is "Match your contact to the public voter file!" (Unless it has been completed, obviously, in which case it should be "Contact is matched to the voter file! Click to un-link"

Then we list the rest, and the ones dependent on being matched to the voter file are... greyed out? A different color? But still legible.

Clicking on each task (even unavailable ones) brings up the detail view as it does now, but the ones not available (either because of date or blocked by no voter match) can't be completed and have a note added indicating why. "You can't complete this task yet!" or "You can't complete this task until your contact is matched to the voter file."

Can we do that?
