### ISSUE TITLE
Is weighted scoring implemented for the voting action?

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/mainstream_relational_gotv#25]
In the instructions, we say, "Contact votes (any which way, early, or on election day): 10-40 pts. depending on the contact's record of voting. Those who vote every election garner fewer points than those who vote infrequently. We're creating a culture of voting here!"

Is that actually implemented? Implementable?

**Comment by jakelowen** [comment]
Yep! Check out the database view that generates points at https://github.com/gpsimpact/mainstream_relational_gotv/blob/master/src/server/src/db/migrations/20180427200124_pv_points_rollup.js
