### ISSUE TITLE
For later, but this cycle: Can we include polling location for each contact?

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/mainstream_relational_gotv#26]
Is that possible? Reliable? It would be valuable.

**Comment by jakelowen** [comment]
Possible, yes.  The voter file has polling place columns we could easily pull in for each contact either through a special display OR by creating tasks.. "Remind this person their polling place is 123 fake st..."

Reliable? I can't vouch for that. Someone should call the KS Sec of State's office and ask if the polling place information found in the state voter file is reliable enough to give out to voters.
