### ISSUE TITLE
Adding tasks via Postico?

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/mainstream_relational_gotv#27]
Can i add task via Postico? I've browsed through the tables exposed there, and it looks like I might be able to, but I'll need a primer on the schema, and a refresher on the task format.

**Comment by jakelowen** [comment]
Yes! You can add tasks to the tasks table.  

pv_id is the id of the user the task is assigned to.

point_value is obvious - just an integer like 1, 10 etc

status is one of 'INCOMPLETE',  'INPROGRESS',  'COMPLETE', 'SKIPPED',
you should default to  'INCOMPLETE'

ignore sequence.. that is no longer used and will be dropped soon.

description is a human readable string description of the task. 

form_schema should look something like: https://github.com/gpsimpact/mainstream_relational_gotv/blob/master/src/server/src/taskDefinitions/exampleFormSchema.json 

not_visible_before and not_visible_after are timestamps.

form_data should remain blank.. that is where collected info is written to.

I am happy to help you parse this structure in more depth.

**Comment by MainStreamDanny** [comment]
So, is there no master template for each task? If I wanted to create a new task that would then replicate across all ambassadors for every contact, how would I do that?

**Comment by MainStreamDanny** [comment]
Which is to say, if there is no pv_id, yet.
