### ISSUE TITLE
Official footer text to change

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/mainstream_relational_gotv#3]
Here is the official forked footer content:

"The Voter to Voter project is part of the Be A Voter initiative of the MainStream Education Foundation. Contact Lindsay with questions at lindsay@mainstreamcoalition.org or call (913) 649-3326."

I don't know if GPS Impact wants credit. If yes, we could append "Development by GPS Impact." or something like that.

"Voter to Voter" should be a link to be-a-voter.org/voter_to_voter
"Be A Voter" should be a link to be-a-voter.org
"MainStream Education Foundation" should be a link to mainstreamcoalition.org
"lindsay@mainstreamcoalition.org" should be a mailto:lindsay@mainstreamcoalition.org link
If it's on there, "GPS Impact" could link to your site

**Comment by MainStreamDanny** [comment]
Also, sorry, can we make it left justified, instead of center justified? Thanks.

**Comment by jakelowen** [comment]
![image](https://user-images.githubusercontent.com/5368008/40734800-10f657f4-63ff-11e8-96e7-414552817ddd.png)

Done!
