### ISSUE TITLE
HEroku export: rename field names for name fields

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/mainstream_relational_gotv#33]
Rename the file names for exports

ambassador_first_name
ambassador_last_name
contact_first_name
contact_last_name
voter_file_first_name
voter_file_middle_name
voter_file_last_name

**Comment by jakelowen** [comment]
Done!   https://dataclips.heroku.com/rvcopsxkmlakirdfufpvgojeiqpk-MainStream-Coalition-entire-cohort
