### ISSUE TITLE
Heroku export: voter data for an organization

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/mainstream_relational_gotv#35]
Have an export for organizations to see the list of their voters being tracked. Each line is a voter, starting with voter name, but also including their ambassador's name.

**Comment by MainStreamDanny** [comment]
I'm not sure how this is different from the current "all data" export, mind you, except that the voter_file_first/middle/last_name fields would come first?

**Comment by MainStreamDanny** [comment]
See the admin_notes field for MainStream's group to see how I envision using these links.

**Comment by jakelowen** [comment]
I think perhaps the way this is different is that we don't attempt to have all the columns in each view.  So for example we can have one view which is just ambassadors. One that is just voters and so on.  Then that one master view which shoves it all together. That way if they just want to see one thing, it is easier to do so.

**Comment by MainStreamDanny** [comment]
I think this is good and done. I'm gonna close it?
