### ISSUE TITLE
Heroku export: can we do math in the export?

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/mainstream_relational_gotv#36]
For example, on an export of ambassadors, is there a way to calculate the, for example, average voter propensity score of all their matched contacts? So, Ambassador Danny has a field at the end, average_voter_propensity that has a value of 2.4. Can we do that?

**Comment by jakelowen** [comment]
Yes, it is absolutely possible to calculate this. However I'd encourage you to think of it as a separate data view than just entire organizational cohort. I typically don't like mixing the "grain" of data, i.e. individual level rows should not have group metrics and vice versa. IF you want to think of a report that has aggregates like:
amb1: points_earned : point_rank_in_org : avg_voter_propensity_score : count_of_contacts : etc etc

I can absolutely make those views.

**Comment by MainStreamDanny** [comment]
I'd like to request that report then: Organization Ambassadors Ranked

amb1: points_earned : point_rank_in_org : avg_voter_propensity_score : count_of_contacts
amb2: etc.

Ordered by... probably last name to start, in case they are looking for a particular ambassador.

**Comment by jakelowen** [comment]
Hows this? https://dataclips.heroku.com/vijrxytwtewcinfcfcgymraledqz-MASTER-ambassador-meta

**Comment by MainStreamDanny** [comment]
I like it! How do I get that made for each org/team? Is it a matter of changing the URL? Do you have to write one for each org/team? Is that a manual process?

I’m currently putting admin_notes in manually for each org/team. So I can put in different URLs for each one, to point to their data. But I need to know what those URLs are, or how to generate them. I’m still adding new teams every day, and hopefully will be for a while.

Thanks!

Danny.

—
Danny Novo
Communications Coordinator
MainStream Coalition
