### ISSUE TITLE
Heroku export: Master export of all data for MainStream admins

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/mainstream_relational_gotv#41]
We'd like a master export of all the stuff. We'd want a link we can follow, but just emailed to us, not linked anywhere from the interface.

Org1:Amb1:Voter1
Org1:Amb1:Voter2
Org1:Amb2:Voter1
Org2:Amb1:Voter1
Org2:Amb2:Voter1
Org2:Amb2:Voter2
Org3... etc.

**Comment by jakelowen** [comment]
Done!   
https://dataclips.heroku.com/mpjvnpjncbtgwiaatjirmceyzcen-MASTER-ADMIN-COHORT

**Comment by MainStreamDanny** [comment]
So, yes, but the results include contacts that have been deleted. I know you keep them for data integrity... is there an easy way to see that they are old? Or can we make this clip not include the deleted contacts?

**Comment by MainStreamDanny** [comment]
Also, we will need to include ambassadors who have no voters in this master list.
