### ISSUE TITLE
Removing orgs: Test Labor Org

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/mainstream_relational_gotv#42]
So, removing orgs... I did it once, it involved a lot of finicky queries I was worried would kill things. But it seems to have worked. I'd like an easier way.

In the meantime, can you quickly remove the "Test Labor Org" organization? We don't want a test account on the list when we are doing the presentations.

Thanks!

**Comment by jakelowen** [comment]
Done!
