### ISSUE TITLE
I can't add labels to indicate priority for an issue

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/mainstream_relational_gotv#46]
I know you said I could add labels, but I've been all over the Github help files, and they all indicate interface elements that just aren't there for me. I must not have high enough permissions on here. Did you have a thought? I think it would be useful (at least to me) to indicate when something is a real issue that is stopping us from proceeding.

**Comment by jakelowen** [comment]
I think it would cost $21 a month to add another collaborator seat. Probably not worth it, right?

**Comment by MainStreamDanny** [comment]
You are correct, not worth it. I’ll just keep pestering you. :)

—
Danny Novo
Communications Coordinator
MainStream Coalition
