### ISSUE TITLE
Change elections in the voter propensity score

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/mainstream_relational_gotv#48]
For the voter propensity score, we want to use the following

General 2014 - Gubernatorial
Primary 2016 - Presidential
General 2016 - Presidential
General 2017 - City/School

**Comment by jakelowen** [comment]
Swapped over to codes: 'GN2016', 'GN2014', 'PR2016', 'CG2017'

This gives the entire state voter file a propensity score distribution of:

![image](https://user-images.githubusercontent.com/5368008/42229891-2c31fc08-7ead-11e8-91bd-6499a339a9c7.png)
