### ISSUE TITLE
Several cases where one email address wants to admin more than one group, possible?

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/mainstream_relational_gotv#49]
So, we have several cases where one person is admin for more than one org. That clearly won't work in the tool the way it is designed, as we use a unique email to assign them to an org on login.

Thoughts? Is there an easy-is fix? Or do we just tell them no, or rather, tell them to use separate email addresses to login to each of their org/Teams?

I think the latter. But you tell me.

**Comment by jakelowen** [comment]
I already anticipated this. When a user has a role with multiple organizations it will ask them to chose an org when they log in.  If you want to experiment, give yourself a permission in to 2 or more orgs, then LOG OUT and log back in and attempt to go to the dashboard.  The log out / log back in part is important.  If it does not work as anticipated, let me know.
