### ISSUE TITLE
For later: Need a faster, programmatic, less error prone way to add links to data results

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/mainstream_relational_gotv#50]
I've just added a bunch of the heroku data links to the admin_notes fields for orgs. Still have several to go. My process involves:

1. tabbing to your open Google Doc
2. copying one link
3. tabbing to my open Notes text editor
4. pasting the link into the proper location in the canned admin notes text I have in Markdown format
5. tabbing back to the Google Doc to select and copy the next link
6. tabbing back to my Notes to insert it into the proper location
7. copying the entirety of the text block
8. tabbing to Postico and finding the proper org's fields, pasting text block into admin_notes field
9. saving changes
10. repeat

This is a little tedious, and a lot prone to errors. In a future iteration, next year, or this year with AI funding, I'd love the following workflow:

1. pasting boilerplate admin_notes text into a global variables table, with some sort of marker for inserting variables, like `"[Your admin links](!!adminlink!!)"`
2. having the system generate unique links to the data output that it dynamically inserts when the content is fetched on the front end (or if that is too much server load, some other way of programmatically generating links to data as new orgs/teams are added, instead of you having to make them by hand, then us having to paste them in)
3. done! woo! drinks all around!

**Comment by jakelowen** [comment]
IMO, we'd avoid all of this once we have an admin dashboard built out because we'd present the data directly in the protected admin area of a team and skip the use of dataclips altogether.
