### ISSUE TITLE
MASTER COHORT list showing many (but not all) duplicates

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/mainstream_relational_gotv#51]
Hey Jake, just looking at the MASTER COHORT list you posted a little while ago, and noted a lot of duplicates. So I went into my dashboard, which had no contacts, and added Brandi, matched her, then added my wife, and did not match her. I waited a minute for heroku to catch up, then loaded the list again. It has four entries fro me as an ambassador, two for Brandi, and two for my wife. As best I can tell from the data presented in the clip, they are identical.

There may be more going on here, as not every voter is duplicated, though many are.

Here is the heroku link I'm using: https://dataclips.heroku.com/mpjvnpjncbtgwiaatjirmceyzcen-MASTER-ADMIN-COHORT

**Comment by MainStreamDanny** [comment]
Good news is, the clips for the individual orgs do not seem to have this issue (at least the one I am an admin on, MainStream Coalition). Maybe I have an old Master Cohort link?

**Comment by MainStreamDanny** [comment]
Also good news, is I don't think they are duplicated in the potential_voters table, either, which suggests it might be a query issue. I looked at the query as displayed, and I don't remember/never knew enough to be sure, but it might be in the Joining? I dunno. Just trying to help.

**Comment by jakelowen** [comment]
I swapped master cohort over to the same query used by the organizational views (only unfiltered to show all users). If duplicates remain, we might verify its not just the same voter being entered over and over again. I know I did that alot during testing.
