### ISSUE TITLE
Date added column

### ISSUE THREAD

**Issue by jakelowen** [gpsimpact/mainstream_relational_gotv#58]
Per Lindsay's email:
Is it possible to add a "date added" to the dataclip with all the voters in our system? When we get the list from the SOS, I'm wondering if we'll be able to differentiate voters who were added pre-primary and voters being added now by new ambassadors?

**Comment by MainStreamDanny** [comment]
So yeah, adding this to the potential_voters table would be great.

**Comment by jakelowen** [comment]
Updated PV table in database and master cohort dataclip to include date the pv was added. Because I just added this to the database, every prior record will show as being added today, but all subsequent records should have proper dates of when they were added.
