### ISSUE TITLE
When a voter is not matched, can we remove the tasks link on the right side?

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/mainstream_relational_gotv#69]
What it says in the subject line. When a voter has been added but not matched, can we have the Tasks link not appear?

**Comment by jakelowen** [comment]
That was the original behavior, but you guys asked me to change it to this current approach on #24 

Please review that discussion in issure #24 and let me know if its still important to refactor this back out.

**Comment by MainStreamDanny** [comment]
Okay, we've discussed this, and you're right, we have gone back and forth on this. Here's what we have decided. We'd like to leave the Tasks list link visible, thank you. But we'd like people to be able to see the tasks if they have not matched the contact yet.

Right now, the behavior is, if you have not matched the contact, when you click on tasks it interrupts with the requirement that you match the contact first. You can't see the list of tasks until you have matched the contact.

The problem with this is if the person is unmatched because they have not registered ,it can take a considerable amount of time after they have registered for them to be listed and matchable. We'd like people to be able to proceed with the tasks anyway.

So, we'd like to maintain the Task 0, Match your contact, but we'd like it to be one among the other tasks. First on the list. When matched, it becomes checked by itself. Yes? Can this be done?
