### ISSUE TITLE
Front page text content

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/mainstream_relational_gotv#7]
Here is text content for the front landing page, where it currently begins "Welcome! This is the main..." etc.

Title text: "Ready to make a difference?"

Body text: "Welcome to the online tool for the non-partisan Voter to Voter project. We are using this website to connect partner organization ambassadors with the every day voters they know. As an ambassador for your organization, you'll have a dashboard where you can identify your friends, family, or peers, and guide them through the process of becoming engaged voters. The tool will let you keep track of their progress, and will provide tips, timely messaging, and optional tasks to help you get them to vote. This project is strictly non-partisan, and the tool imposes no specific position or policy messaging, except, of course, that voting is important.

If you have any questions, you can [learn more about Voter to Voter at our website](https://www.be-a-voter.org/voter_to_voter)."

Second Title text: "Voter to Voter Partner Organizations"

Body text: "Find your organization in the list below and click to learn more about them, contact them, or register as an ambassador for their Voter to Voter effort. Thank you for being engaged."

**Comment by jakelowen** [comment]
![image](https://user-images.githubusercontent.com/5368008/40735012-af5d2aee-63ff-11e8-8384-da2ec69dca2b.png)

Done!

**Comment by MainStreamDanny** [comment]
Awesome. You haven't pushed a new build though, right? That's why I'm not seeing it?
