### ISSUE TITLE
Clarification on primary vs general tasks and what we want to display

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/mainstream_relational_gotv#72]
So, in answer to your email:

1. Yes, we want every potential voter to have both sets of tasks in their record. That seems like the easiest approach, and is cool. We might even be able to use that to correlate for who was active in the Primary (e.g., if their Ambassador marked any of their Primary tasks).

2. Yes, we want the Primary tasks "deactivated," though that was your word, and I'm not 100% sure what you meant by it. Basically, in the tasks interface, we want only the General tasks to be visible. The Primary tasks can exist on their database record, but we don't want them displaying, even if they are greyed out or unclickable. That'll just be confusing.

**Comment by jakelowen** [comment]
This is proving to be tougher than I thought and would require a big refactor. As it is, there is no concept of a task being tied to either the primary or general cycle. A task is just a task with properties like status and date last updated.  The only thing I can think to do here without a big refactor is to have the UI "disable" any task that has been completed prior to the primary election date.  

We can then go in an run a database query to insert new tasks for any contact whose "primary era" task is already complete.  I.e. for those contacts with a complete "tell about upcoming election" task completed prior to 8/7 now go create a new task of the same type.  Would that work?

**Comment by jakelowen** [comment]
Closing. Previously fixed.
