### ISSUE TITLE
Add a link to the home page text

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/mainstream_relational_gotv#73]
Where it says on the home page:

2. If you've heard about Voter to Voter but want to learn more, visit our Be A Voter website and sign up to get an overview training of the effort and this tool.

The text:

visit our Be A Voter website

Should be linked to:

https://www.be-a-voter.org/voter_to_voter

Sorry that wasn't in my original dump of that text.

**Comment by jakelowen** [comment]
Fixed.
