### ISSUE TITLE
Can the admin_notes field for orgs have HTML?

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/mainstream_relational_gotv#9]
If the admin_notes field is where we place specific notes for admins to see when they log in to their otherwise ambassador-style dashboard, can that field take HTML? So I can add links, or formatting?

**Comment by jakelowen** [comment]
admin_notes can accept and will render markdown content. So links, paragraphs, headers, bullets anything!  Cheat sheet at: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
